import { INPUT_LABELSProps } from "./types/type";

export const INPUT_LABELS: INPUT_LABELSProps = {
  "phone_number": "Phone number",
  "lastname": "Lastname",
  "firstname": "Name",
  "middlename": "Middlename",
  "password": "Password",
  "email_address": "Email",
  "inn": "TAX ID",
};

export const CONVERTER = {
  а: 'a',
  б: 'b',
  в: 'v',
  г: 'g',
  д: 'd',
  е: 'e',
  ё: 'e',
  ж: 'zh',
  з: 'z',
  и: 'i',
  й: 'y',
  к: 'k',
  л: 'l',
  м: 'm',
  н: 'n',
  о: 'o',
  п: 'p',
  р: 'r',
  с: 's',
  т: 't',
  у: 'u',
  ф: 'f',
  х: 'h',
  ц: 'c',
  ч: 'ch',
  ш: 'sh',
  щ: 'sch',
  ь: '',
  ы: 'y',
  ъ: '',
  э: 'e',
  ю: 'yu',
  я: 'ya',

  А: 'A',
  Б: 'B',
  В: 'V',
  Г: 'G',
  Д: 'D',
  Е: 'E',
  Ё: 'E',
  Ж: 'Zh',
  З: 'Z',
  И: 'I',
  Й: 'Y',
  К: 'K',
  Л: 'L',
  М: 'M',
  Н: 'N',
  О: 'O',
  П: 'P',
  Р: 'R',
  С: 'S',
  Т: 'T',
  У: 'U',
  Ф: 'F',
  Х: 'H',
  Ц: 'C',
  Ч: 'Ch',
  Ш: 'Sh',
  Щ: 'Sch',
  Ь: '',
  Ы: 'Y',
  Ъ: '',
  Э: 'E',
  Ю: 'Yu',
  Я: 'Ya',
};

export const SUMSUB_URL = "https://api.sumsub.com";

export enum colorTable {
  charcoalBlack = "#222222",
  black = "#111111",
  anthraciteGray = "#474747",
  moonGrey = "#8e8e8e",
  nobleOchre = "#DAC481",
  goldenHaze = "#FFEBB0",
  ivory = "#FFF2C9",
  textSecondary = "#525252",
  greyContour = "#E7E7E7",
  lightGrey = "#F9F9F9",
  red = "#D72D40",
  red_10 = "#d3312f",
  redLight = "#FBEAEC",
  textIconAccentRed = "#D43E50",
  green_50 = "#00A582",
  lightGreen = "#E6F5F2",
  green_40 = "#00BD93",
  orange = "#FFA000",
  lightOrange = "#FFF5E5",
  white = "#ffffff",
  white_10 = "#F2F5FA",
  white_20 = "#F7F7F7",
  whiteGrey = "#FFFFFFCC",
  lightGrey_90 = "#566C91",
  lightGrey_10 = "#F5F7FA",
  lightGrey_30 = "#E9EFF5",
  lightGrey_50 = "#CFDBEA",
  lightGrey_40 = "#8E8E8E",
  lightGrey_5 = "#eeeeee",
  lightGrey_70 = "#93969A",
  lightGrey_60 = "#F0F4F8",
  lightGrey_20 = "#F4F7FA",
  lightGrey_100 = "#D2D8E2",
  darkGrey_10 = "#6E7A88",
  lightBlue = "#E9F4FF",
  shadow = "#00000014",
  blue_10 = "#1F4151",
  blue_20 = "#006AEF",
  blue_30 = "#71B3FD",
  blue_40 = "#006cef",
  misteryBlue = "#5A7494",
  seaBlue = "#0e1b21",
  darkBlue = "#0F222B",
  blackBlue = "#111924",
  dialogBackground = "rgba(0, 0, 0, 0.5)",
  transparentBlack_008 = "rgba(0, 0, 0, 0.08)",
  transparentBlack_004 = "rgba(0, 0, 0, 0.04)",
  transparent = "transparent",
  white_30 = "#F4F7FC",
  yellowLight = "#FCF2CC",
  green = "#00A582",
}
